config/routes.rb
Homes::Application.routes.draw do
 
   root to: 'addresses#index'

   resources :addresses
 
end

app/models/address.rb
class Address < ActiveRecord::Base
	
	has_many :housings
	has_many :people, :through => :housings
	accepts_nested_attributes_for :housings, allow_destroy: true

  after_destroy :clean_up

  private
  def clean_up
    self.housings.each do |housing|
      housing.person.delete
      housing.delete
    end
  end

end

app/models/housing.rb
class Housing < ActiveRecord::Base

	belongs_to :person
	belongs_to :address
	
	accepts_nested_attributes_for :person, allow_destroy: true
end

app/models/person.rb
class Person < ActiveRecord::Base

	has_one :housing
	has_one :address, :through => :housing
		
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

	def index		
		@addresses = Address.all

	end
	
	def new
		@address = Address.new
	end
	
	def create
		@address = Address.create address_params
		if @address.valid?
			redirect_to addresses_path
		else
			render :new
		end
	end	
	
	def edit
		@address= Address.find params[:id]
	end
	
	def update
		@address = Address.find params[:id]
		if @address.update_attributes(address_params)
			redirect_to addresses_path
		else
			render :edit
		end	
	end
	
	def destroy
		@address= Address.find params[:id]
		@address.destroy
		redirect_to addresses_path
	end
	

	
	
	private
	def address_params
		params.require(:address).permit!
	end
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add-fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/views/addresses/_form.html.erb
<%=form_for @address do |f| %>
	<%= f.label :address %><br>
	<%= f.text_area :address %><br>
	<%= f.label :zipcode %>
	<%= f.text_field :zipcode %><br>
	<%= f.fields_for :housings do |builder|%>
    <%= render 'housing_fields', f: builder %>
	<%end%>
  <%= link_to_add_fields('Add Person', f, :housings) %>
	<br>
	<%= f.submit "Save" %>
	<% unless @address.valid? %>
		<%= @address.errors.full_messages %>
	<%end%>
<%end%>

app/views/addresses/_housing_fields.html.erb
<fieldset>
  <%= f.label :status %>
  <%= f.text_field :status %>
  
  <% f.object.build_person unless f.object.person.present? %>

  <%= f.fields_for :person do |p| %>
    <p> <%= p.label :firstname %> <%= p.text_field :firstname %> </p>
    <p> <%= p.label :lastname %> <%= p.text_field :lastname %> </p>
    <p> <%= p.label :birthyear %> <%= p.text_field :birthyear %> </p>
  <% end %>
  <p>
    <%= f.hidden_field :_destroy %>
    <%= link_to 'Remove', '#', class: 'remove-fields', remote: true %>
  </p>
</fieldset>

app/views/addresses/_person.html.erb
<fieldset>
  <%= f.label :firstname, "Firstname" %><br/>
  <%= f.text_field :firstname %><br/>
  <%= f.label :lastname, "Lastname" %><br/>
  <%= f.text_field :lastname %><br/>
  <%= f.label :birthyear, "Birthyear" %><br/>
  <%= f.text_field :birthyear %><br/>
</fieldset>

app/views/addresses/edit.html.erb
<h1>Edit household</h1>
<%= render "form" %>

app/views/addresses/index.html.erb
<h1>Addresses</h1>


<% @addresses.each do |address| %>
	<fieldset>
		<legend>
			<%=address.zipcode -%>, 
			<%=address.address %>
		</legend>
		<h4>List of residents:</h4>
		<ul>
			<%address.people.map do |person|%>
				<li>
					<%=person.firstname%>
					<%=person.lastname%>
					<%=person.birthyear%>
					<br>
					<span>Status:</span>
          <%= person.housing.status %>
				</li>
			<%end%>
		</ul>
		<%=link_to "Edit", edit_address_path(address)%>
    <%=link_to "Delete", address_path(address), method: :delete, data: { confirm: 'Are you sure?' } %>
	</fieldset>
	<br>
<% end %>
<%=link_to "Add new household", new_address_path %>

app/views/addresses/new.html.erb
<h1>Add new household</h1>
<%= render "form" %>

app/views/housings/index.html.erb
<h1>Households</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>Hello</h1>
<ul>
<% @people.each do |person| %>
	<li>
		<%=person[:firstname]%>
		<%=person[:lastname]%>
	</li>
<%end%>
</ul>